apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: "aws"
        - name: SERVICE1
          value: "project1.default.svc.cluster.local"
        image: deb538/eks_routing:gateway
        imagePullPolicy: Always
        name: gateway
        ports:
        - name: liveness-port
          containerPort: 8081
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: gateway
  name: gateway
  namespace: default
spec:
  ports:
  - # nodePort: 30701 
    port: 8081 
    protocol: TCP
    targetPort: 8081
  selector:
    app: gateway
  type: LoadBalancer
