spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: app1
        uri: http://project1.default.svc.cluster.local:8083/
        predicates:
        - Path=/api/v1/app1/name
      - id: app2
        uri: http://localhost:8082/
        predicates:
        - Path=/api/v1/app2/name
    
server:
  port: 8081

management:
  endpoint:
    health:
      probes:
        enabled: true 

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true



